POST http://localhost:8080/api/v1/system/category.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTI2NTE1MDEsImxhc3RfbG9naW5faWQiOiI5MThlZmFiYy0zYjhlLTQ2NDItOTVlZC1lMTBjMWIwYzQyYzQiLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiNzE2OWIwOTMtMmMxYS00ZWQ2LWFlYmUtOWFhNjg0YmM5NjQxIn0.imGr15uU_edVAET0ogsKtP5s5sDbdxhIvDo-rudIhMfZglLWYbfk9ZE9cbDmX2E6Rgz6In9IBNlmaDqlK_m6VX9eQI0PdgA6J5WUvfiO2IuOsKnb5BQ5JiTbV8xbvBY4Xkuo-Hp72sqn4AcpFoc8cq-Fuor2uX7x34BoG6s_oUqLdD6sv4a3cB4UA9UIJitC8I06zNJ-F4G7AVC7CjWnZgulERegL38VeOoDY3wlgYrvABdMPXVQHp86r3y0cQ1GwmdZgOMy0tHix_k8r2KYLULYk5tKF75zh-LReFjzzp-9aTMqhtHe6VIGRkNW2z4I461T7eNeo_9oqrUoDEYnxg

    {    "name" : "Go Fiber120s222ss",
        "index": 2
    }