GET http://localhost:8080/api/v1/system/category.json?page=1&limit=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTI2NzEwODUsImxhc3RfbG9naW5faWQiOiIyNjdjZmNkMy1iZGFjLTQ2ZTQtYmZhOS0zMjY1YTkyOWVmOWIiLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiNzY4ODE0NzQtZjkzMS00YTgwLTg0YWEtMWFkNGY1NjFmYmEwIn0.d9foQJ6A-5jxjpPFZxKTmYocai0pc9ProGNs6pa72qzraZjmxwkvzSnggoHrY1CVXd_HZKmx6QcfkDFs5jdFJr-9A8PKfjTvQ5622C4CGUqpoEjyVcsf8ZrKr1nt2NZNq4q4az_7T3oa8CgK2r-ZyBKwyKIQv8xg0tXkSUtIaZRdHqFAVgGpauuMnjmzGm8FjTeMU__nVY6xFC7riRYW9nrQ88sx45f9NZR15F_GdPzmqDWbOu_02tyoH6nDqNmmYPwUkg6LUDXvU0ML-5L7Talonjywfw6IUgkaEAQROR38scURQPT0EQsP2PoUlus9WiEdIbvPw4BxyXsA4mP6lA
