GET http://localhost:8080/api/v1/system/post/detail.json?id=8490a1e3-2067-4924-b992-929b723886e9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTI3OTk5MjYsImxhc3RfbG9naW5faWQiOiIyYjRjMjA1OC05YjM5LTRiMGYtYmZkZi1hNmZhOGZlNDFiNTQiLCJyb2xlIjoiYWRtaW4iLCJ1c2VyX2lkIjoiNzE2OWIwOTMtMmMxYS00ZWQ2LWFlYmUtOWFhNjg0YmM5NjQxIn0.MWwDkwvcDEGRVAKjRZ1vE0x3T7j-9XV8pakKmH4s15O28y2W2jYBZjlnbNKqMfCll4ANIHQ2Kz2RKUVrMN2kjUsmj2vv_SCcoKFuGuieGFeyHLg8uv6i6GE41SwKRvAgPj1se3Q-0TtZbXW_roMwsoHxNuCDAiv25UBd1dyPEXoLl6UgexeFvMlQh9UYY3oQ5-kgsX7ZdofVxyP-3cmMamLtJIVYjrxadrJK-8h7PpcrXWpTd2il84UGuuj0bc_M0hC7Sejc08fhvEY74eS_vZCWlH87VG2e_9btajwvBzK0TRg7WcEmL0lvsk00GihtWTGjwyVjMp3wcqE97CY5DA