POST http://localhost:3006/api/account/register.json
Authorization: Bearer 192929
x-api-key: ENqKRmbFzPAbXN5VRfdq7hVNEjztVRV1
Content-Type: application/json

{
    "email" : "alidoan21@gmail.com",
    "password" : "alo123",
}