POST http://localhost:8080/api/account/register.json
Authorization: Bearer 192929
x-api-key: ENqKRmbFzPAbXN5VRfdq7hVNEjztVRV1
Content-Type: application/json

{
    "email" : "alidoan1@gmail.com",
    "password" : "alo1133"
}